@ECHO OFF. ECHO. 
REM P2 JM_CNN_s2s
set PYTHONPATH=E:\Wind
ECHO lanza programa desde multipledata
REM cd E:\Wind\Scripts\MultipleData
cd E:\Wind\Minotauro
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3
python JM_ExtractConfig.py --exp JM_CNN_sep_2l_FULL --bsc --nconfig 140 --machine mino --jph 3

